export const ENDPOINTS = {
  AUTH: {
    REGISTER: '/api/auth/register',
    LOGIN: '/api/auth/login',
    REFRESH: '/api/auth/refresh',
    FORGOT_PASSWORD: '/api/auth/forgot-password',
    RESET_PASSWORD: '/api/auth/reset-password',
    LOGOUT: '/api/auth/logout',
  },
  USER: {
    ME: '/api/users/me',
    UPDATE_ME: '/api/users/me',
    CHANGE_PASSWORD: '/api/users/me/password',
    UPLOAD_AVATAR: '/api/users/me/avatar',
    VERIFY: '/api/users/me/verify',
  },
  LANDLORD_APPLICATIONS: {
    ROOT: '/api/landlord-applications',
    ME: '/api/landlord-applications/me',
    APPROVE: (id: string) => `/api/landlord-applications/${id}/approve`,
    REJECT: (id: string) => `/api/landlord-applications/${id}/reject`,
  },
  TEAM: {
    ROOT: '/api/team',
    INVITE: '/api/team',
    UPDATE: (id: string) => `/api/team/${id}`,
    UPDATE_PERMISSIONS: (id: string) => `/api/team/${id}/permissions`,
    UPDATE_PROPERTIES: (id: string) => `/api/team/${id}/properties`,
    DELETE: (id: string) => `/api/team/${id}`,
  },
  PROPERTIES: {
    ROOT: '/api/properties',
    DETAILS: (id: string) => `/api/properties/${id}`,
    STATUS: (id: string) => `/api/properties/${id}/status`,
    IMAGES: (id: string) => `/api/properties/${id}/images`,
    UNITS: (id: string) => `/api/properties/${id}/units`,
  },
  UNITS: {
    ROOT: '/api/units',
    DETAILS: (id: string) => `/api/units/${id}`,
    STATUS: (id: string) => `/api/units/${id}/status`,
    IMAGES: (id: string) => `/api/units/${id}/images`,
  },
  TENANCIES: {
    ROOT: '/api/tenancies',
    DETAILS: (id: string) => `/api/tenancies/${id}`,
    MY: '/api/tenancies/my',
    CONFIRM_CHECKIN: '/api/tenancies/confirm-checkin',
    CHECKOUT: (id: string) => `/api/tenancies/${id}/checkout`,
    COMMENTS: (id: string) => `/api/tenancies/${id}/comments`,
    ROOMMATES: (id: string) => `/api/tenancies/${id}/roommates`,
  },
  INQUIRIES: {
    ROOT: '/api/inquiries',
    DETAILS: (id: string) => `/api/inquiries/${id}`,
    PROPERTY: (propertyId: string) => `/api/inquiries/property/${propertyId}`,
  },
  MESSAGES: {
    CONVERSATION: (conversationId: string) => `/api/messages/conversation/${conversationId}/messages`,
  },
  VISITS: {
    ROOT: '/api/visits',
    DETAILS: (id: string) => `/api/visits/${id}`,
    PROPERTY: (propertyId: string) => `/api/visits/property/${propertyId}`,
    APPROVE: (id: string) => `/api/visits/${id}/approve`,
    SCHEDULE: (id: string) => `/api/visits/${id}/schedule`,
    ASSIGN: (id: string) => `/api/visits/${id}/assign`,
    COMPLETE: (id: string) => `/api/visits/${id}/complete`,
    CANCEL: (id: string) => `/api/visits/${id}/cancel`,
    NO_SHOW: (id: string) => `/api/visits/${id}/no-show`,
  },
  APPLICATIONS: {
    ROOT: '/api/applications',
    DETAILS: (id: string) => `/api/applications/${id}`,
    REVIEW: (id: string) => `/api/applications/${id}/review`,
    APPROVE: (id: string) => `/api/applications/${id}/approve`,
    REJECT: (id: string) => `/api/applications/${id}/reject`,
  },
  CONTRACTS: {
    ROOT: '/api/contracts',
    DETAILS: (id: string) => `/api/contracts/${id}`,
    CREATE_FROM_APP: '/api/contracts/create-from-application',
    SIGN: (id: string) => `/api/contracts/${id}/sign`,
    STATUS: (id: string) => `/api/contracts/${id}/status`,
    GENERATE_PDF: (id: string) => `/api/contracts/${id}/generate-pdf`,
    DOWNLOAD: (id: string) => `/api/contracts/${id}/download`,
  },
  BILLS: {
    ROOT: '/api/bills',
    DETAILS: (id: string) => `/api/bills/${id}`,
    GENERATE: '/api/bills/generate',
    PAY: (id: string) => `/api/bills/${id}/pay`,
  },
  TICKETS: {
    ROOT: '/api/tickets',
    DETAILS: (id: string) => `/api/tickets/${id}`,
    ASSIGN: (id: string) => `/api/tickets/${id}/assign`,
    UPDATE: (id: string) => `/api/tickets/${id}/updates`,
    RESOLVE: (id: string) => `/api/tickets/${id}/resolve`,
    CLOSE: (id: string) => `/api/tickets/${id}/close`,
  },
  INVENTORY: {
    ROOT: '/api/inventory',
    DETAILS: (id: string) => `/api/inventory/${id}`,
    RECORDS: '/api/inventory/records',
    METRICS: '/api/inventory/metrics',
  },
  UTILITIES: {
    ROOT: '/api/utilities',
    READINGS: '/api/utilities/readings',
    METRICS: '/api/utilities/metrics',
  },
  PUBLIC: {
    LISTINGS: '/api/public/listings',
    PROPERTY_DETAILS: (id: string) => `/api/public/listings/${id}`,
    UNIT_DETAILS: (id: string) => `/api/public/listings/unit/${id}`,
  },
  DOCUMENTS: {
    ROOT: '/api/documents',
    DETAILS: (id: string) => `/api/documents/${id}`,
  },
  SECURITY: {
    INCIDENTS: '/api/security/incidents',
    INCIDENT_DETAILS: (id: string) => `/api/security/incidents/${id}`,
    CONTACTS: (propertyId: string) => `/api/security/contacts/${propertyId}`,
  },
  FINANCIALS: {
    ROOT: '/api/financials',
    SUMMARY: '/api/financials/summary',
    MONTHLY: '/api/financials/monthly',
    BY_PROPERTY: '/api/financials/by-property',
  }
} as const;
