import React, { useState } from 'react';
import { TextField, Box, Typography } from '@mui/material';
import FormDialog from '../../../components/FormDialog';
import { format } from 'date-fns';

interface AutoGenerateDialogProps {
  open: boolean;
  onClose: () => void;
  onSubmit: (monthYear: string) => Promise<any>;
}

export default function AutoGenerateDialog({ open, onClose, onSubmit }: AutoGenerateDialogProps) {
  const [monthYear, setMonthYear] = useState<string>(
    format(new Date(), 'yyyy-MM')
  );
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      await onSubmit(monthYear);
      onClose();
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <FormDialog
      open={open}
      title="Generate Bills Automatically"
      onClose={onClose}
      onSubmit={handleSubmit}
      submitText="Generate Bills"
      loading={loading}
      maxWidth="xs"
    >
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
        <Typography variant="body2" color="text.secondary">
          This action will analyze all active tenancies and generate standard recurring rent bills for the selected month. It skips tenancies that already have bills for this period.
        </Typography>

        <TextField
          label="Billing Month"
          type="month"
          value={monthYear}
          onChange={(e) => setMonthYear(e.target.value)}
          fullWidth
          required
          InputLabelProps={{
            shrink: true,
          }}
        />
      </Box>
    </FormDialog>
  );
}
