import { useEffect, useState } from 'react';
import { Box, Button, TextField, MenuItem, IconButton, Typography, InputAdornment } from '@mui/material';
import { Add as AddIcon, Autorenew as AutorenewIcon, Search as SearchIcon, Visibility as VisibilityIcon } from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import { format } from 'date-fns';

import PageHeader from '../../../components/PageHeader';
import DataTable from '../../../components/DataTable';
import type { Column } from '../../../components/DataTable';
import StatusBadge from '../../../components/StatusBadge';
import type { Bill } from '../../../../domain/entities/Bill';
import { useBilling } from '../../../../application/hooks/useBilling';
import AutoGenerateDialog from './AutoGenerateDialog';

export default function BillList() {
  const navigate = useNavigate();
  const { bills, loading, fetchBills, generateBills } = useBilling();
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('All');
  const [generateDialogOpen, setGenerateDialogOpen] = useState(false);

  useEffect(() => {
    fetchBills();
  }, [fetchBills]);

  const filteredBills = bills.filter(bill => {
    let match = true;
    if (statusFilter !== 'All' && bill.status !== statusFilter) match = false;
    // Simplistic search fallback for mock data
    if (searchTerm && !bill.id.includes(searchTerm)) match = false;
    return match;
  });

  const columns: Column<Bill>[] = [
    { id: 'billingPeriod', label: 'Period', format: (_, row) => format(new Date(row.billingPeriod.start), 'MMM yyyy') },
    { id: 'type', label: 'Type', format: (val) => String(val).toUpperCase() },
    { id: 'totalAmount', label: 'Total', format: (val) => `₱${Number(val).toLocaleString()}` },
    { id: 'paidAmount', label: 'Paid', format: (val) => `₱${Number(val).toLocaleString()}` },
    { 
      id: 'balanceAmount', 
      label: 'Balance', 
      format: (val, row) => (
        <Typography variant="body2" sx={{ fontWeight: 600, color: row.status === 'overdue' ? 'error.main' : 'inherit' }}>
          ₱{Number(val).toLocaleString()}
        </Typography>
      ) 
    },
    { id: 'dueDate', label: 'Due Date', format: (val) => format(new Date(val as string | Date), 'MMM dd, yyyy') },
    { 
      id: 'status', 
      label: 'Status', 
      format: (val) => <StatusBadge status={val as any} />
    },
    {
      id: 'actions',
      label: 'Actions',
      align: 'right',
      format: (_, row) => (
        <IconButton size="small" onClick={() => navigate(`/hub/billing/${row.id}`)} color="primary">
          <VisibilityIcon fontSize="small" />
        </IconButton>
      )
    }
  ];

  return (
    <Box sx={{ maxWidth: 1200, mx: 'auto', p: { xs: 2, md: 3 } }}>
      <PageHeader
        title="Bill Management"
        subtitle="Manage tenancies, collect rent, and oversee utility payments."
        action={
          <Box sx={{ display: 'flex', gap: 2 }}>
            <Button
              variant="outlined"
              startIcon={<AutorenewIcon />}
              onClick={() => setGenerateDialogOpen(true)}
            >
              Generate Bills
            </Button>
            <Button
              variant="contained"
              startIcon={<AddIcon />}
              onClick={() => {
                // manual bill creation mock or route
              }}
            >
              Create Manual Bill
            </Button>
          </Box>
        }
      />

      <Box sx={{ display: 'flex', gap: 2, mb: 3, flexWrap: 'wrap' }}>
        <TextField
          placeholder="Search by ID or Tenant..."
          size="small"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          sx={{ minWidth: 300 }}
          InputProps={{
            startAdornment: <InputAdornment position="start"><SearchIcon /></InputAdornment>
          }}
        />
        <TextField
          select
          label="Status"
          size="small"
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
          sx={{ minWidth: 150 }}
        >
          <MenuItem value="All">All Statuses</MenuItem>
          <MenuItem value="unpaid">Unpaid</MenuItem>
          <MenuItem value="partial">Partial</MenuItem>
          <MenuItem value="paid">Paid</MenuItem>
          <MenuItem value="overdue">Overdue</MenuItem>
        </TextField>
      </Box>

      <DataTable
        columns={columns}
        data={filteredBills}
        loading={loading}
        emptyTitle="No Bills Found"
        emptyDescription="Try adjusting your filters or generate new bills for this period."
      />

      <AutoGenerateDialog
        open={generateDialogOpen}
        onClose={() => setGenerateDialogOpen(false)}
        onSubmit={generateBills}
      />
    </Box>
  );
}
