import mongoose, { Schema, Document } from 'mongoose';

export type BillType = 'rent' | 'utility' | 'penalty' | 'combined';
export type BillStatus = 'unpaid' | 'partial' | 'paid' | 'overdue';

export interface IUtilityBreakdown {
  electricity?: {
    previousReading?: number;
    currentReading?: number;
    consumption?: number;
    rate?: number;
    amount: number;
  };
  water?: {
    previousReading?: number;
    currentReading?: number;
    consumption?: number;
    rate?: number;
    amount: number;
  };
  internet?: {
    amount: number;
  };
  others?: {
    description?: string;
    amount: number;
  };
}

export interface IBillingPeriod {
  start: Date;
  end: Date;
}

export interface IBill extends Document {
  tenancyId: mongoose.Types.ObjectId;
  propertyId: mongoose.Types.ObjectId;
  unitId: mongoose.Types.ObjectId;
  contractId?: mongoose.Types.ObjectId;
  type: BillType;
  billingPeriod: IBillingPeriod;
  rentAmount: number;
  utilityAmount: number;
  penaltyAmount: number;
  totalAmount: number;
  paidAmount: number;
  balanceAmount: number;
  status: BillStatus;
  dueDate: Date;
  utilityBreakdown?: IUtilityBreakdown;
  isAutoGenerated: boolean;
  receiptUrl?: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

const UtilityBreakdownSchema = new Schema<IUtilityBreakdown>(
  {
    electricity: {
      previousReading: { type: Number },
      currentReading: { type: Number },
      consumption: { type: Number },
      rate: { type: Number },
      amount: { type: Number, default: 0 }
    },
    water: {
      previousReading: { type: Number },
      currentReading: { type: Number },
      consumption: { type: Number },
      rate: { type: Number },
      amount: { type: Number, default: 0 }
    },
    internet: {
      amount: { type: Number, default: 0 }
    },
    others: {
      description: { type: String },
      amount: { type: Number, default: 0 }
    }
  },
  { _id: false }
);

const BillingPeriodSchema = new Schema<IBillingPeriod>(
  {
    start: { type: Date, required: true },
    end: { type: Date, required: true }
  },
  { _id: false }
);

const BillSchema = new Schema<IBill>(
  {
    tenancyId: {
      type: Schema.Types.ObjectId,
      ref: 'Tenancy',
      required: true
    },
    propertyId: {
      type: Schema.Types.ObjectId,
      ref: 'Property',
      required: true
    },
    unitId: {
      type: Schema.Types.ObjectId,
      ref: 'Unit',
      required: true
    },
    contractId: {
      type: Schema.Types.ObjectId,
      ref: 'Contract'
    },
    type: {
      type: String,
      enum: ['rent', 'utility', 'penalty', 'combined'],
      required: true
    },
    billingPeriod: {
      type: BillingPeriodSchema,
      required: true
    },
    rentAmount: {
      type: Number,
      default: 0,
      min: 0
    },
    utilityAmount: {
      type: Number,
      default: 0,
      min: 0
    },
    penaltyAmount: {
      type: Number,
      default: 0,
      min: 0
    },
    totalAmount: {
      type: Number,
      required: true,
      min: 0
    },
    paidAmount: {
      type: Number,
      default: 0,
      min: 0
    },
    balanceAmount: {
      type: Number,
      required: true,
      min: 0
    },
    status: {
      type: String,
      enum: ['unpaid', 'partial', 'paid', 'overdue'],
      default: 'unpaid'
    },
    dueDate: {
      type: Date,
      required: true
    },
    utilityBreakdown: {
      type: UtilityBreakdownSchema
    },
    isAutoGenerated: {
      type: Boolean,
      default: false
    },
    receiptUrl: {
      type: String
    },
    notes: {
      type: String,
      trim: true
    }
  },
  { timestamps: true }
);

// Indexes for efficient querying
BillSchema.index({ tenancyId: 1, status: 1 });
BillSchema.index({ propertyId: 1, status: 1 });
BillSchema.index({ unitId: 1, status: 1 });
BillSchema.index({ contractId: 1 });
BillSchema.index({ status: 1, dueDate: 1 });
BillSchema.index({ dueDate: 1, status: 1 });
BillSchema.index({ type: 1, status: 1 });
BillSchema.index({ createdAt: -1 });
// Prevent duplicate auto-generated bills for same tenancy + period
BillSchema.index(
  { tenancyId: 1, type: 1, 'billingPeriod.start': 1, 'billingPeriod.end': 1 },
  {
    unique: true,
    partialFilterExpression: { isAutoGenerated: true }
  }
);

export const Bill = mongoose.model<IBill>('Bill', BillSchema);
