import cron from 'node-cron';
import { Prisma } from '@prisma/client';
import prisma from '../config/prisma';

// This file has no HTTP route and no golden-fixture coverage (cron-driven
// only, wired from server.ts's `initScheduler()`). Ported carefully and
// verified by direct invocation of each private job function instead (see
// the task report). Each of the 5 jobs is a self-contained rewrite of the
// original Mongoose function of the same name/shape -- deliberately NOT
// delegated to billing.service.ts's own `autoGenerateMonthlyBills` or
// visit.service.ts's own `createVisitReminders`, even though both exist and
// cover superficially similar ground: their notification copy differs from
// this file's own (`'New Bill Generated'`/`'Visit Reminder'` there vs
// `'Monthly Bill Generated'`/`'Visit Tomorrow'` here), so reusing them would
// silently change this file's user-facing text. See the task report for the
// full comparison.

// ─────────────────────────────────────────────────────────────
//  Job 1: Monthly Bill Auto-Generation (1st of each month, 2:00 AM)
// ─────────────────────────────────────────────────────────────

const autoGenerateMonthlyBills = async () => {
  console.log('[Scheduler] Running monthly bill auto-generation...');
  try {
    const now = new Date();
    const month = now.getMonth() + 1;
    const year = now.getFullYear();

    const tenancies = await prisma.tenancy.findMany({
      where: { status: 'checked_in' },
      include: { property: true, contract: true },
    });

    let created = 0;
    let skipped = 0;

    for (const tenancy of tenancies) {
      try {
        const contract = tenancy.contract;
        const property = tenancy.property;
        if (!contract || !property) {
          skipped++;
          continue;
        }

        const start = new Date(year, month - 1, 1);
        const end = new Date(year, month, 0);
        const dueDay = property.dueDay ?? 5;
        const maxDay = new Date(year, month, 0).getDate();
        const dueDate = new Date(year, month - 1, Math.min(dueDay, maxDay));

        const existing = await prisma.bill.findFirst({
          where: {
            tenancyId: tenancy.id,
            type: 'rent',
            isAutoGenerated: true,
            billingPeriodStart: start,
            billingPeriodEnd: end,
          },
        });

        if (existing) {
          skipped++;
          continue;
        }

        const rentAmount = new Prisma.Decimal(contract.monthlyRent);

        try {
          // Bill.create + Notification.create: two writes under Mongoose
          // with no atomicity between them -- wrapped in one
          // prisma.$transaction, same pattern as every other
          // create-plus-notify path in this migration (a crash between the
          // two could otherwise leave a bill generated with no tenant
          // notification, or vice versa).
          await prisma.$transaction(async (tx) => {
            await tx.bill.create({
              data: {
                tenancyId: tenancy.id,
                propertyId: property.id,
                unitId: tenancy.unitId,
                contractId: contract.id,
                type: 'rent',
                billingPeriodStart: start,
                billingPeriodEnd: end,
                rentAmount,
                utilityAmount: 0,
                penaltyAmount: 0,
                totalAmount: rentAmount,
                paidAmount: 0,
                balanceAmount: rentAmount,
                status: 'unpaid',
                dueDate,
                isAutoGenerated: true,
              },
            });

            await tx.notification.create({
              data: {
                userId: tenancy.userId,
                type: 'billing',
                title: 'Monthly Bill Generated',
                message: `Your rent bill for ${start.toLocaleDateString('en-PH', { month: 'long', year: 'numeric' })} has been generated. Amount: ₱${rentAmount.toNumber().toLocaleString()}.`,
                link: '/u/my-bills',
              },
            });
          });

          created++;
        } catch (err: any) {
          // A genuine TOCTOU race against the existence check above trips
          // the `bills_auto_period_uniq` partial unique index (P2002) --
          // treat that exactly like the pre-check's own "skipped" outcome
          // rather than logging it as a hard per-tenancy error.
          if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === 'P2002') {
            skipped++;
          } else {
            throw err;
          }
        }
      } catch (err: any) {
        console.error(`[Scheduler] Bill gen error for tenancy ${tenancy.id}:`, err.message);
      }
    }

    console.log(`[Scheduler] Bill auto-gen complete: ${created} created, ${skipped} skipped.`);
  } catch (err) {
    console.error('[Scheduler] Monthly bill auto-gen failed:', err);
  }
};

// ─────────────────────────────────────────────────────────────
//  Job 2: Daily Late Fee Check (every day, 3:00 AM)
// ─────────────────────────────────────────────────────────────

const checkAndApplyLateFees = async () => {
  console.log('[Scheduler] Running daily late fee check...');
  try {
    const now = new Date();

    // Find unpaid or partial bills past due date that haven't been marked overdue
    const overdueBills = await prisma.bill.findMany({
      where: {
        status: { in: ['unpaid', 'partial'] },
        dueDate: { lt: now },
      },
      include: { property: { select: { lateFeePercent: true } } },
    });

    let applied = 0;

    for (const bill of overdueBills) {
      try {
        if ((bill.status as string) === 'overdue') continue; // Already processed (unreachable given the query filter above; kept for parity with the original's own defensive check)

        const property = bill.property;
        const lateFeePercent = property ? property.lateFeePercent.toNumber() : 5;
        const rentAmount = bill.rentAmount.toNumber();
        const utilityAmount = bill.utilityAmount.toNumber();
        const penalty = Math.round((rentAmount + utilityAmount) * (lateFeePercent / 100) * 100) / 100;

        const newPenaltyAmount = bill.penaltyAmount.toNumber() + penalty;
        const newTotalAmount = rentAmount + utilityAmount + newPenaltyAmount;
        const newBalanceAmount = newTotalAmount - bill.paidAmount.toNumber();

        // Bill.save (penalty/total/balance/status) + Notification.create:
        // two writes under Mongoose with no atomicity between them --
        // wrapped in one prisma.$transaction, same reasoning as Job 1.
        await prisma.$transaction(async (tx) => {
          await tx.bill.update({
            where: { id: bill.id },
            data: {
              penaltyAmount: newPenaltyAmount,
              totalAmount: newTotalAmount,
              balanceAmount: newBalanceAmount,
              status: 'overdue',
            },
          });

          const tenancy = await tx.tenancy.findUnique({ where: { id: bill.tenancyId }, select: { userId: true } });
          if (tenancy) {
            await tx.notification.create({
              data: {
                userId: tenancy.userId,
                type: 'billing',
                title: 'Late Fee Applied',
                message: `A late fee of ₱${penalty.toLocaleString()} has been applied to your overdue bill. New balance: ₱${newBalanceAmount.toLocaleString()}.`,
                link: '/u/my-bills',
              },
            });
          }
        });

        applied++;
      } catch (err: any) {
        console.error(`[Scheduler] Late fee error for bill ${bill.id}:`, err.message);
      }
    }

    console.log(`[Scheduler] Late fee check complete: ${applied} fees applied.`);
  } catch (err) {
    console.error('[Scheduler] Late fee check failed:', err);
  }
};

// ─────────────────────────────────────────────────────────────
//  Job 3: Daily Visit Reminders (every day, 8:00 AM)
// ─────────────────────────────────────────────────────────────

const sendVisitReminders = async () => {
  console.log('[Scheduler] Running daily visit reminders...');
  try {
    const now = new Date();
    const tomorrow = new Date(now);
    tomorrow.setDate(tomorrow.getDate() + 1);

    // Start and end of tomorrow
    const tomorrowStart = new Date(tomorrow.getFullYear(), tomorrow.getMonth(), tomorrow.getDate());
    const tomorrowEnd = new Date(tomorrowStart.getTime() + 24 * 60 * 60 * 1000);

    const upcomingVisits = await prisma.visitRequest.findMany({
      where: {
        status: 'scheduled',
        scheduledDate: { gte: tomorrowStart, lt: tomorrowEnd },
      },
      include: { property: { select: { name: true, landlordId: true } } },
    });

    let sent = 0;

    // Sequential, non-atomic notification creates per visit -- matches the
    // original's own lack of atomicity here exactly. These are pure
    // notification fan-outs (no other row is written alongside them), same
    // class of write as visit.service.ts's own `createVisitReminders()`,
    // which documents the identical choice not to wrap these in a
    // transaction.
    for (const visit of upcomingVisits) {
      try {
        const property = visit.property;

        // Notify the visitor
        await prisma.notification.create({
          data: {
            userId: visit.userId,
            type: 'visit',
            title: 'Visit Tomorrow',
            message: `Reminder: Your scheduled visit to ${property?.name || 'the property'} is tomorrow.`,
            link: '/u/my-visits',
          },
        });

        // Notify the landlord
        if (property?.landlordId) {
          await prisma.notification.create({
            data: {
              userId: property.landlordId,
              type: 'visit',
              title: 'Visit Tomorrow',
              message: `Reminder: A scheduled visit for ${property?.name || 'your property'} is tomorrow.`,
              link: '/hub/bookings',
            },
          });
        }

        // Notify assigned staff
        if (visit.assignedStaffId) {
          await prisma.notification.create({
            data: {
              userId: visit.assignedStaffId,
              type: 'visit',
              title: 'Assigned Visit Tomorrow',
              message: `Reminder: You have a scheduled visit at ${property?.name || 'the property'} tomorrow.`,
              link: '/hub/bookings',
            },
          });
        }

        sent++;
      } catch (err: any) {
        console.error(`[Scheduler] Visit reminder error for visit ${visit.id}:`, err.message);
      }
    }

    console.log(`[Scheduler] Visit reminders complete: ${sent} reminders sent.`);
  } catch (err) {
    console.error('[Scheduler] Visit reminders failed:', err);
  }
};

// ─────────────────────────────────────────────────────────────
//  Job 4: Daily Checkout Reminders (7/3/1 days before contract end)
// ─────────────────────────────────────────────────────────────

const sendCheckoutReminders = async () => {
  console.log('[Scheduler] Running daily checkout reminders...');
  try {
    const now = new Date();
    const reminderDays = [7, 3, 1];
    let sent = 0;

    for (const daysAhead of reminderDays) {
      const targetDate = new Date(now);
      targetDate.setDate(targetDate.getDate() + daysAhead);

      const targetStart = new Date(targetDate.getFullYear(), targetDate.getMonth(), targetDate.getDate());
      const targetEnd = new Date(targetStart.getTime() + 24 * 60 * 60 * 1000);

      const expiringContracts = await prisma.contract.findMany({
        where: {
          status: 'active',
          endDate: { gte: targetStart, lt: targetEnd },
        },
        include: { property: { select: { name: true, landlordId: true } } },
      });

      // Pure notification fan-out, no other row written -- kept
      // non-atomic per this job's own class of write (see Job 3's comment).
      for (const contract of expiringContracts) {
        try {
          const property = contract.property;

          // Notify tenant
          await prisma.notification.create({
            data: {
              userId: contract.userId,
              type: 'contract',
              title: `Contract Ending in ${daysAhead} Day${daysAhead > 1 ? 's' : ''}`,
              message: `Your lease at ${property?.name || 'the property'} ends in ${daysAhead} day${daysAhead > 1 ? 's' : ''}. Please coordinate with your landlord regarding renewal or checkout.`,
              link: '/u/my-contracts',
            },
          });

          // Notify landlord
          if (property?.landlordId) {
            await prisma.notification.create({
              data: {
                userId: property.landlordId,
                type: 'contract',
                title: `Tenant Contract Ending in ${daysAhead} Day${daysAhead > 1 ? 's' : ''}`,
                message: `A tenant's contract at ${property?.name || 'your property'} expires in ${daysAhead} day${daysAhead > 1 ? 's' : ''}. Prepare for checkout or discuss renewal.`,
                link: '/hub/contracts',
              },
            });
          }

          sent++;
        } catch (err: any) {
          console.error(`[Scheduler] Checkout reminder error for contract ${contract.id}:`, err.message);
        }
      }
    }

    console.log(`[Scheduler] Checkout reminders complete: ${sent} reminders sent.`);
  } catch (err) {
    console.error('[Scheduler] Checkout reminders failed:', err);
  }
};

// ─────────────────────────────────────────────────────────────
//  Job 5: Daily Auto-Renewal Offer (30 days before contract expiry)
// ─────────────────────────────────────────────────────────────

const sendAutoRenewalOffers = async () => {
  console.log('[Scheduler] Running daily auto-renewal offer check...');
  try {
    const now = new Date();
    const target = new Date(now);
    target.setDate(target.getDate() + 30);

    const targetStart = new Date(target.getFullYear(), target.getMonth(), target.getDate());
    const targetEnd = new Date(targetStart.getTime() + 24 * 60 * 60 * 1000);

    const expiringContracts = await prisma.contract.findMany({
      where: {
        status: 'active',
        endDate: { gte: targetStart, lt: targetEnd },
      },
      include: { property: { select: { name: true, landlordId: true } } },
    });

    let sent = 0;

    // Pure notification fan-out, no other row written -- kept non-atomic
    // per this job's own class of write (see Job 3's comment).
    for (const contract of expiringContracts) {
      try {
        const property = contract.property;

        // Notify tenant about renewal
        await prisma.notification.create({
          data: {
            userId: contract.userId,
            type: 'contract',
            title: 'Contract Renewal Available',
            message: `Your lease at ${property?.name || 'the property'} expires in 30 days. Would you like to renew? Contact your landlord to discuss renewal terms.`,
            link: '/u/my-contracts',
          },
        });

        // Notify landlord
        if (property?.landlordId) {
          await prisma.notification.create({
            data: {
              userId: property.landlordId,
              type: 'contract',
              title: 'Tenant Eligible for Renewal',
              message: `A tenant's contract at ${property?.name || 'your property'} expires in 30 days. Consider reaching out to offer renewal terms.`,
              link: '/hub/contracts',
            },
          });
        }

        sent++;
      } catch (err: any) {
        console.error(`[Scheduler] Renewal offer error for contract ${contract.id}:`, err.message);
      }
    }

    console.log(`[Scheduler] Auto-renewal offers complete: ${sent} offers sent.`);
  } catch (err) {
    console.error('[Scheduler] Auto-renewal offers failed:', err);
  }
};

// ─────────────────────────────────────────────────────────────
//  Scheduler Init
// ─────────────────────────────────────────────────────────────

export const initScheduler = () => {
  const enabled = process.env.ENABLE_CRON === 'true';

  if (!enabled) {
    console.log('[Scheduler] Cron jobs DISABLED (set ENABLE_CRON=true to enable).');
    return;
  }

  console.log('[Scheduler] Initializing cron jobs...');

  // 1. Monthly bill auto-generation — 1st of each month at 2:00 AM
  cron.schedule('0 2 1 * *', autoGenerateMonthlyBills, {
    timezone: 'Asia/Manila',
  });
  console.log('[Scheduler]   ✓ Monthly bill auto-gen (1st of month, 2:00 AM)');

  // 2. Daily late fee check — every day at 3:00 AM
  cron.schedule('0 3 * * *', checkAndApplyLateFees, {
    timezone: 'Asia/Manila',
  });
  console.log('[Scheduler]   ✓ Daily late fee check (3:00 AM)');

  // 3. Daily visit reminders — every day at 8:00 AM
  cron.schedule('0 8 * * *', sendVisitReminders, {
    timezone: 'Asia/Manila',
  });
  console.log('[Scheduler]   ✓ Daily visit reminders (8:00 AM)');

  // 4. Daily checkout reminders — every day at 9:00 AM
  cron.schedule('0 9 * * *', sendCheckoutReminders, {
    timezone: 'Asia/Manila',
  });
  console.log('[Scheduler]   ✓ Daily checkout reminders (9:00 AM)');

  // 5. Daily auto-renewal offers — every day at 10:00 AM
  cron.schedule('0 10 * * *', sendAutoRenewalOffers, {
    timezone: 'Asia/Manila',
  });
  console.log('[Scheduler]   ✓ Daily auto-renewal offers (10:00 AM)');

  console.log('[Scheduler] All cron jobs initialized successfully.');
};

// Test-only escape hatches: direct invocation of the private job functions,
// since this file has no HTTP route and no golden-fixture coverage (see the
// task report for the manual verification run against seeded data).
export const __testables = {
  autoGenerateMonthlyBills,
  checkAndApplyLateFees,
  sendVisitReminders,
  sendCheckoutReminders,
  sendAutoRenewalOffers,
};
