import cron from 'node-cron';
import { Bill } from '../models/Bill';
import { Tenancy } from '../models/Tenancy';
import { Contract } from '../models/Contract';
import { VisitRequest } from '../models/VisitRequest';
import { Notification } from '../models/Notification';
import { Property } from '../models/Property';

// ─────────────────────────────────────────────────────────────
//  Job 1: Monthly Bill Auto-Generation (1st of each month, 2:00 AM)
// ─────────────────────────────────────────────────────────────

const autoGenerateMonthlyBills = async () => {
  console.log('[Scheduler] Running monthly bill auto-generation...');
  try {
    const now = new Date();
    const month = now.getMonth() + 1;
    const year = now.getFullYear();

    const tenancies: any[] = await Tenancy.find({ status: 'checked_in' })
      .populate('propertyId')
      .populate('contractId');

    let created = 0;
    let skipped = 0;

    for (const tenancy of tenancies) {
      try {
        const contract = tenancy.contractId;
        const property = tenancy.propertyId;
        if (!contract || !property) { skipped++; continue; }

        const start = new Date(year, month - 1, 1);
        const end = new Date(year, month, 0);
        const dueDay = property.billingSettings?.dueDay || 5;
        const maxDay = new Date(year, month, 0).getDate();
        const dueDate = new Date(year, month - 1, Math.min(dueDay, maxDay));

        const existing = await Bill.findOne({
          tenancyId: tenancy._id,
          type: 'rent',
          isAutoGenerated: true,
          'billingPeriod.start': start,
          'billingPeriod.end': end
        });

        if (existing) { skipped++; continue; }

        const rentAmount = contract.monthlyRent || 0;

        await Bill.create({
          tenancyId: tenancy._id,
          propertyId: property._id,
          unitId: tenancy.unitId,
          contractId: contract._id,
          type: 'rent',
          billingPeriod: { start, end },
          rentAmount,
          utilityAmount: 0,
          penaltyAmount: 0,
          totalAmount: rentAmount,
          paidAmount: 0,
          balanceAmount: rentAmount,
          status: 'unpaid',
          dueDate,
          isAutoGenerated: true
        });

        await Notification.create({
          userId: tenancy.userId,
          type: 'billing',
          title: 'Monthly Bill Generated',
          message: `Your rent bill for ${start.toLocaleDateString('en-PH', { month: 'long', year: 'numeric' })} has been generated. Amount: ₱${rentAmount.toLocaleString()}.`,
          link: '/u/my-bills'
        });

        created++;
      } catch (err: any) {
        console.error(`[Scheduler] Bill gen error for tenancy ${tenancy._id}:`, err.message);
      }
    }

    console.log(`[Scheduler] Bill auto-gen complete: ${created} created, ${skipped} skipped.`);
  } catch (err) {
    console.error('[Scheduler] Monthly bill auto-gen failed:', err);
  }
};

// ─────────────────────────────────────────────────────────────
//  Job 2: Daily Late Fee Check (every day, 3:00 AM)
// ─────────────────────────────────────────────────────────────

const checkAndApplyLateFees = async () => {
  console.log('[Scheduler] Running daily late fee check...');
  try {
    const now = new Date();

    // Find unpaid or partial bills past due date that haven't been marked overdue
    const overdueBills: any[] = await Bill.find({
      status: { $in: ['unpaid', 'partial'] },
      dueDate: { $lt: now }
    }).populate('propertyId');

    let applied = 0;

    for (const bill of overdueBills) {
      try {
        if (bill.status === 'overdue') continue; // Already processed

        const property = bill.propertyId;
        const lateFeePercent = property?.billingSettings?.lateFeePercent || 5;
        const penalty = Math.round((bill.rentAmount + bill.utilityAmount) * (lateFeePercent / 100) * 100) / 100;

        bill.penaltyAmount += penalty;
        bill.totalAmount = bill.rentAmount + bill.utilityAmount + bill.penaltyAmount;
        bill.balanceAmount = bill.totalAmount - bill.paidAmount;
        bill.status = 'overdue';
        await bill.save();

        const tenancy: any = await Tenancy.findById(bill.tenancyId);
        if (tenancy) {
          await Notification.create({
            userId: tenancy.userId,
            type: 'billing',
            title: 'Late Fee Applied',
            message: `A late fee of ₱${penalty.toLocaleString()} has been applied to your overdue bill. New balance: ₱${bill.balanceAmount.toLocaleString()}.`,
            link: '/u/my-bills'
          });
        }

        applied++;
      } catch (err: any) {
        console.error(`[Scheduler] Late fee error for bill ${bill._id}:`, err.message);
      }
    }

    console.log(`[Scheduler] Late fee check complete: ${applied} fees applied.`);
  } catch (err) {
    console.error('[Scheduler] Late fee check failed:', err);
  }
};

// ─────────────────────────────────────────────────────────────
//  Job 3: Daily Visit Reminders (every day, 8:00 AM)
// ─────────────────────────────────────────────────────────────

const sendVisitReminders = async () => {
  console.log('[Scheduler] Running daily visit reminders...');
  try {
    const now = new Date();
    const tomorrow = new Date(now);
    tomorrow.setDate(tomorrow.getDate() + 1);

    // Start and end of tomorrow
    const tomorrowStart = new Date(tomorrow.getFullYear(), tomorrow.getMonth(), tomorrow.getDate());
    const tomorrowEnd = new Date(tomorrowStart.getTime() + 24 * 60 * 60 * 1000);

    const upcomingVisits: any[] = await VisitRequest.find({
      status: 'scheduled',
      scheduledDate: { $gte: tomorrowStart, $lt: tomorrowEnd }
    }).populate('propertyId', 'name landlordId');

    let sent = 0;

    for (const visit of upcomingVisits) {
      try {
        // Notify the visitor
        await Notification.create({
          userId: visit.userId,
          type: 'visit',
          title: 'Visit Tomorrow',
          message: `Reminder: Your scheduled visit to ${visit.propertyId?.name || 'the property'} is tomorrow.`,
          link: '/u/my-visits'
        });

        // Notify the landlord
        if (visit.propertyId?.landlordId) {
          await Notification.create({
            userId: visit.propertyId.landlordId,
            type: 'visit',
            title: 'Visit Tomorrow',
            message: `Reminder: A scheduled visit for ${visit.propertyId?.name || 'your property'} is tomorrow.`,
            link: '/hub/bookings'
          });
        }

        // Notify assigned staff
        if (visit.assignedStaffId) {
          await Notification.create({
            userId: visit.assignedStaffId,
            type: 'visit',
            title: 'Assigned Visit Tomorrow',
            message: `Reminder: You have a scheduled visit at ${visit.propertyId?.name || 'the property'} tomorrow.`,
            link: '/hub/bookings'
          });
        }

        sent++;
      } catch (err: any) {
        console.error(`[Scheduler] Visit reminder error for visit ${visit._id}:`, err.message);
      }
    }

    console.log(`[Scheduler] Visit reminders complete: ${sent} reminders sent.`);
  } catch (err) {
    console.error('[Scheduler] Visit reminders failed:', err);
  }
};

// ─────────────────────────────────────────────────────────────
//  Job 4: Daily Checkout Reminders (7/3/1 days before contract end)
// ─────────────────────────────────────────────────────────────

const sendCheckoutReminders = async () => {
  console.log('[Scheduler] Running daily checkout reminders...');
  try {
    const now = new Date();
    const reminderDays = [7, 3, 1];
    let sent = 0;

    for (const daysAhead of reminderDays) {
      const targetDate = new Date(now);
      targetDate.setDate(targetDate.getDate() + daysAhead);

      const targetStart = new Date(targetDate.getFullYear(), targetDate.getMonth(), targetDate.getDate());
      const targetEnd = new Date(targetStart.getTime() + 24 * 60 * 60 * 1000);

      const expiringContracts: any[] = await Contract.find({
        status: 'active',
        endDate: { $gte: targetStart, $lt: targetEnd }
      }).populate('propertyId', 'name landlordId');

      for (const contract of expiringContracts) {
        try {
          // Notify tenant
          await Notification.create({
            userId: contract.userId,
            type: 'contract',
            title: `Contract Ending in ${daysAhead} Day${daysAhead > 1 ? 's' : ''}`,
            message: `Your lease at ${contract.propertyId?.name || 'the property'} ends in ${daysAhead} day${daysAhead > 1 ? 's' : ''}. Please coordinate with your landlord regarding renewal or checkout.`,
            link: '/u/my-contracts'
          });

          // Notify landlord
          if (contract.propertyId?.landlordId) {
            await Notification.create({
              userId: contract.propertyId.landlordId,
              type: 'contract',
              title: `Tenant Contract Ending in ${daysAhead} Day${daysAhead > 1 ? 's' : ''}`,
              message: `A tenant's contract at ${contract.propertyId?.name || 'your property'} expires in ${daysAhead} day${daysAhead > 1 ? 's' : ''}. Prepare for checkout or discuss renewal.`,
              link: '/hub/contracts'
            });
          }

          sent++;
        } catch (err: any) {
          console.error(`[Scheduler] Checkout reminder error for contract ${contract._id}:`, err.message);
        }
      }
    }

    console.log(`[Scheduler] Checkout reminders complete: ${sent} reminders sent.`);
  } catch (err) {
    console.error('[Scheduler] Checkout reminders failed:', err);
  }
};

// ─────────────────────────────────────────────────────────────
//  Job 5: Daily Auto-Renewal Offer (30 days before contract expiry)
// ─────────────────────────────────────────────────────────────

const sendAutoRenewalOffers = async () => {
  console.log('[Scheduler] Running daily auto-renewal offer check...');
  try {
    const now = new Date();
    const target = new Date(now);
    target.setDate(target.getDate() + 30);

    const targetStart = new Date(target.getFullYear(), target.getMonth(), target.getDate());
    const targetEnd = new Date(targetStart.getTime() + 24 * 60 * 60 * 1000);

    const expiringContracts: any[] = await Contract.find({
      status: 'active',
      endDate: { $gte: targetStart, $lt: targetEnd }
    }).populate('propertyId', 'name landlordId');

    let sent = 0;

    for (const contract of expiringContracts) {
      try {
        // Notify tenant about renewal
        await Notification.create({
          userId: contract.userId,
          type: 'contract',
          title: 'Contract Renewal Available',
          message: `Your lease at ${contract.propertyId?.name || 'the property'} expires in 30 days. Would you like to renew? Contact your landlord to discuss renewal terms.`,
          link: '/u/my-contracts'
        });

        // Notify landlord
        if (contract.propertyId?.landlordId) {
          await Notification.create({
            userId: contract.propertyId.landlordId,
            type: 'contract',
            title: 'Tenant Eligible for Renewal',
            message: `A tenant's contract at ${contract.propertyId?.name || 'your property'} expires in 30 days. Consider reaching out to offer renewal terms.`,
            link: '/hub/contracts'
          });
        }

        sent++;
      } catch (err: any) {
        console.error(`[Scheduler] Renewal offer error for contract ${contract._id}:`, err.message);
      }
    }

    console.log(`[Scheduler] Auto-renewal offers complete: ${sent} offers sent.`);
  } catch (err) {
    console.error('[Scheduler] Auto-renewal offers failed:', err);
  }
};

// ─────────────────────────────────────────────────────────────
//  Scheduler Init
// ─────────────────────────────────────────────────────────────

export const initScheduler = () => {
  const enabled = process.env.ENABLE_CRON === 'true';

  if (!enabled) {
    console.log('[Scheduler] Cron jobs DISABLED (set ENABLE_CRON=true to enable).');
    return;
  }

  console.log('[Scheduler] Initializing cron jobs...');

  // 1. Monthly bill auto-generation — 1st of each month at 2:00 AM
  cron.schedule('0 2 1 * *', autoGenerateMonthlyBills, {
    timezone: 'Asia/Manila'
  });
  console.log('[Scheduler]   ✓ Monthly bill auto-gen (1st of month, 2:00 AM)');

  // 2. Daily late fee check — every day at 3:00 AM
  cron.schedule('0 3 * * *', checkAndApplyLateFees, {
    timezone: 'Asia/Manila'
  });
  console.log('[Scheduler]   ✓ Daily late fee check (3:00 AM)');

  // 3. Daily visit reminders — every day at 8:00 AM
  cron.schedule('0 8 * * *', sendVisitReminders, {
    timezone: 'Asia/Manila'
  });
  console.log('[Scheduler]   ✓ Daily visit reminders (8:00 AM)');

  // 4. Daily checkout reminders — every day at 9:00 AM
  cron.schedule('0 9 * * *', sendCheckoutReminders, {
    timezone: 'Asia/Manila'
  });
  console.log('[Scheduler]   ✓ Daily checkout reminders (9:00 AM)');

  // 5. Daily auto-renewal offers — every day at 10:00 AM
  cron.schedule('0 10 * * *', sendAutoRenewalOffers, {
    timezone: 'Asia/Manila'
  });
  console.log('[Scheduler]   ✓ Daily auto-renewal offers (10:00 AM)');

  console.log('[Scheduler] All cron jobs initialized successfully.');
};
