import type { Tenancy } from './Tenancy';

export type BillType = 'rent' | 'utility' | 'penalty' | 'combined';
export type BillStatus = 'unpaid' | 'partial' | 'paid' | 'overdue';

export interface ReadingBreakdown {
  previousReading?: number;
  currentReading?: number;
  consumption?: number;
  rate?: number;
  amount: number;
}

export interface UtilityBreakdown {
  electricity?: ReadingBreakdown;
  water?: ReadingBreakdown;
  internet?: { amount: number };
  others?: { description?: string; amount: number };
}

export interface Bill {
  id: string;
  tenancyId: string;
  tenancy?: Tenancy;
  propertyId: string;
  unitId: string;
  contractId?: string;
  
  type: BillType;
  billingPeriod: {
    start: string | Date;
    end: string | Date;
  };
  
  rentAmount: number;
  utilityAmount: number;
  penaltyAmount: number;
  totalAmount: number;
  paidAmount: number;
  balanceAmount: number;
  
  status: BillStatus;
  dueDate: string | Date;
  
  utilityBreakdown?: UtilityBreakdown;
  isAutoGenerated: boolean;
  notes?: string;
  
  createdAt: string | Date;
  updatedAt: string | Date;
}
